---
blank_issues_enabled: false
contact_links:
  - name: shenlong Community Support
    url: https://github.com/keep-starknet-strange/shenlong/discussions
    about: Please ask and answer questions here.
